// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qL-SVsTQBcH3ggt090dPFFceXsCB1DA',
    appId: '1:1027264268287:web:3449af8d87720e0abbc9ca',
    messagingSenderId: '1027264268287',
    projectId: 'decors-4da56',
    authDomain: 'decors-4da56.firebaseapp.com',
    storageBucket: 'decors-4da56.firebasestorage.app',
    measurementId: 'G-FDTH6TNF9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBra70ZNg_lRfZg7lWATeSqKC0c51MPiec',
    appId: '1:1027264268287:android:b7d11da3c182ab1fbbc9ca',
    messagingSenderId: '1027264268287',
    projectId: 'decors-4da56',
    storageBucket: 'decors-4da56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-Gs0TCtKU-zZndkMaWkKyNzVtO3tbD4',
    appId: '1:1027264268287:ios:07ba4a3774acdb52bbc9ca',
    messagingSenderId: '1027264268287',
    projectId: 'decors-4da56',
    storageBucket: 'decors-4da56.firebasestorage.app',
    iosBundleId: 'com.example.decora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-Gs0TCtKU-zZndkMaWkKyNzVtO3tbD4',
    appId: '1:1027264268287:ios:07ba4a3774acdb52bbc9ca',
    messagingSenderId: '1027264268287',
    projectId: 'decors-4da56',
    storageBucket: 'decors-4da56.firebasestorage.app',
    iosBundleId: 'com.example.decora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6qL-SVsTQBcH3ggt090dPFFceXsCB1DA',
    appId: '1:1027264268287:web:b39051d251342684bbc9ca',
    messagingSenderId: '1027264268287',
    projectId: 'decors-4da56',
    authDomain: 'decors-4da56.firebaseapp.com',
    storageBucket: 'decors-4da56.firebasestorage.app',
    measurementId: 'G-GXDLV4VTGT',
  );
}
